# Generated by Django 5.1.2 on 2024-11-04 23:39

import django.core.validators
import menu_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='ssn',
            field=menu_app.fields.SSNField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_ssn', message='SSN must be in the format XXX-XX-XXXX', regex='^\\d{3}-\\d{2}-\\d{4}$')]),
        ),
    ]
