# Generated by Django 5.1.3 on 2024-11-08 21:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_manager_ssn'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='pay_rate',
            field=models.DecimalField(decimal_places=2, default=7.5, max_digits=5),
        ),
        migrations.AddField(
            model_name='manager',
            name='pin',
            field=models.CharField(default='0000', max_length=4, validators=[django.core.validators.RegexValidator(message='PIN must be exactly 4 digits.', regex='^\\d{4}$')]),
        ),
        migrations.CreateModel(
            name='ManagerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in', models.DateTimeField()),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('day', models.DateField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.manager')),
            ],
        ),
    ]
