# Generated by Django 5.1.3 on 2024-11-08 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_pay_rate_timeentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pin',
            field=models.CharField(default=0, max_length=4, validators=[django.core.validators.RegexValidator(regex='^\\d{4}')]),
        ),
    ]
