# Generated by Django 5.1.3 on 2024-11-08 19:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pin',
            field=models.CharField(default='0000', max_length=4, validators=[django.core.validators.RegexValidator(message='PIN must be exactly 4 digits.', regex='^\\d{4}$')]),
        ),
    ]
